- id: ty-check
  name: ty check
  description: ""
  entry: ty check
  language: python
  types: [python]
  args: []
  require_serial: false
  additional_dependencies: ["ty==0.0.2"]
  minimum_pre_commit_version: "0"
